version: '3.9'

services:

  db:
    image: mongo
    restart: always
    ports:
      - '27014:27014'
    volumes:
      - db:/var/lib/mongo

  app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    image: socail-network
    depends_on:
      - db
    links:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/app/

volumes:
  db:
    driver: local

