version: '3.9'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - '27014:27014'
    volumes:
      - db:/var/lib/mongo

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db:/var/lib/redis

  app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    image: social_network
    depends_on:
      - mongo
      - redis
    links:
      - redis
      - mongo
    ports:
      - '3000:3000'
      - '4000:4000'
    volumes:
      - ./:/app/

volumes:
  mongo:
    driver: local
  redis:
    driver: local