version: '3.9'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis

  influxdb:
    image: influxdb
    restart: always
    ports:
      - '8086:8086'
    volumes:
      - influxdb:/var/lib/influxdb

  src:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: src
    image: social_network
    depends_on:
      - mongo
      - redis
      - influxdb
    links:
      - redis
      - mongo
      - influxdb
    ports:
      - '3000:3000'
      - '4000:4000'
      - '17892:17892'
      - '80:80'
    volumes:
      - ./:/src/

volumes:
  mongo:
    driver: local
  redis:
    driver: local
  influxdb:
    driver: local