const OR = 'OR',
    COMMA = ',',
    AND = 'AND',
    ASC = 'ASC',
    IN = 'IN (?)',
    DESC = 'DESC',
    LIKE = 'LIKE',
    NULL = 'NULL',
    EQUAL_TO = '=',
    WHERE = 'WHERE',
    LESS_THAN = '<',
    LIMIT = 'LIMIT',
    OFFSET = 'OFFSET',
    GREATER_THAN = '>',
    NOT_EQUAL_TO = '<>',
    CASCADE = 'CASCADE',
    BETWEEN = 'BETWEEN',
    QUESTION_MARK = '?',
    COMMENT = 'COMMENT',
    RESTRICT = 'RESTRICT',
    ORDER_BY = 'ORDER BY',
    NOT_NULL = 'NOT NULL',
    NO_ACTION = 'NO ACTION',
    DOUBLE_QUESTION_MARK = '??',
    LESS_THAN_OR_EQUAL_TO = '<=',
    IF_NOT_EXISTS = 'IF NOT EXISTS',
    GREATER_THAN_OR_EQUAL_TO = '>=',
    AUTO_INCREMENT = 'AUTO_INCREMENT';

let int = 'int',
    char = 'char',  // 0 - 255
    varchar = 'varchar',
    date = 'date',  // 2022-03-20
    time = 'time',  // 23:55:54
    boolean = 'boolean',
    datetime = 'datetime';  // 2022-03-20 20:32:42

module.exports = {

    OR: OR,
    IN: IN,
    AND: AND,
    ASC: ASC,
    NULL: NULL,
    DESC: DESC,
    LIKE: LIKE,
    COMMA: COMMA,
    WHERE: WHERE,
    LIMIT: LIMIT,
    OFFSET: OFFSET,
    CASCADE: CASCADE,
    COMMENT: COMMENT,
    BETWEEN: BETWEEN,
    RESTRICT: RESTRICT,
    NOT_NULL: NOT_NULL,
    ORDER_BY: ORDER_BY,
    EQUAL_TO: EQUAL_TO,
    LESS_THAN: LESS_THAN,
    NO_ACTION: NO_ACTION,
    NOT_EQUAL_TO: NOT_EQUAL_TO,
    GREATER_THAN: GREATER_THAN,
    IF_NOT_EXISTS: IF_NOT_EXISTS,
    QUESTION_MARK: QUESTION_MARK,
    AUTO_INCREMENT: AUTO_INCREMENT,
    DOUBLE_QUESTION_MARK: DOUBLE_QUESTION_MARK,
    LESS_THAN_OR_EQUAL_TO: LESS_THAN_OR_EQUAL_TO,
    GREATER_THAN_OR_EQUAL_TO: GREATER_THAN_OR_EQUAL_TO,


    int: int,
    date: date,
    time: time,
    char: char,
    boolean: boolean,
    varchar: varchar,
    datetime: datetime

}